class FoodItem {
  String foodName;

  FoodItem(this.foodName);
}

List<FoodItem> foods = [
    FoodItem('Peaches'),
    FoodItem('Orange'),
    FoodItem('Apples'),
    FoodItem('Strawberries'),
    FoodItem('Raspberries'),
    FoodItem('Bananas'),
    FoodItem('Tomato'),
    FoodItem('Blueberries'),
    FoodItem('Blackberries'),
    FoodItem('Cherries'),
    FoodItem('Grapes'),
    FoodItem('Lemons'),
    FoodItem('Mangoes'),
    FoodItem('Papayas'),
    FoodItem('Pineapple'),
    FoodItem('Kiwi'),
    FoodItem('Watermelon'),
    FoodItem('Cantaloupe'),
    FoodItem('Honeydew'),
    FoodItem('Apricots'),
    FoodItem('Plums'),
    FoodItem('Nectarines'),
    FoodItem('Pears'),
    FoodItem('Figs'),
    FoodItem('Dates'),
    FoodItem('Pomegranates'),
    FoodItem('Persimmons'),
    FoodItem('Cranberries'),
    FoodItem('Gooseberries'),
    FoodItem('Currants'),
    FoodItem('Mulberries'),
    FoodItem('Quinces'),
    FoodItem('Lychee'),
    FoodItem('Passion Fruit'),
    FoodItem('Guava'),
    FoodItem('Dragon Fruit'),
    FoodItem('Star Fruit'),
    FoodItem('Rambutan'),
    FoodItem('Durian'),
    FoodItem('Jackfruit'),
    FoodItem('Avocado'),
    FoodItem('Coconut'),
    FoodItem('Olives'),
    FoodItem('Cucumbers'),
    FoodItem('Zucchini'),
    FoodItem('Eggplant'),
    FoodItem('Bell Peppers'),
    FoodItem('Chili Peppers'),
    FoodItem('Pumpkin'),
    FoodItem('Butternut Squash'),
    FoodItem('Acorn Squash'),
    FoodItem('Spaghetti Squash'),
    FoodItem('Kale'),
    FoodItem('Spinach'),
    FoodItem('Lettuce'),
    FoodItem('Arugula'),
    FoodItem('Swiss Chard'),
    FoodItem('Collard Greens'),
    FoodItem('Mustard Greens'),
    FoodItem('Cabbage'),
    FoodItem('Brussels Sprouts'),
    FoodItem('Broccoli'),
    FoodItem('Cauliflower'),
    FoodItem('Radishes'),
    FoodItem('Carrots'),
    FoodItem('Parsnips'),
    FoodItem('Beets'),
    FoodItem('Turnips'),
    FoodItem('Rutabagas'),
    FoodItem('Sweet Potatoes'),
    FoodItem('Yams'),
    FoodItem('Potatoes'),
    FoodItem('Onions'),
    FoodItem('Garlic'),
    FoodItem('Leeks'),
    FoodItem('Shallots'),
    FoodItem('Scallions'),
    FoodItem('Celery'),
    FoodItem('Fennel'),
    FoodItem('Artichokes'),
    FoodItem('Asparagus'),
    FoodItem('Green Beans'),
    FoodItem('Snow Peas'),
    FoodItem('Sugar Snap Peas'),
    FoodItem('Peas'),
    FoodItem('Okra'),
    FoodItem('Corn'),
    FoodItem('Mushrooms'),
    FoodItem('Portobello Mushrooms'),
    FoodItem('Shiitake Mushrooms'),
    FoodItem('Oyster Mushrooms'),
    FoodItem('Enoki Mushrooms'),
    FoodItem('Button Mushrooms'),
    FoodItem('Crimini Mushrooms'),
    FoodItem('Porcini Mushrooms'),
    FoodItem('Chanterelle Mushrooms'),
    FoodItem('Morel Mushrooms'),
    FoodItem('Truffles'),
    FoodItem('Ginger'),
    FoodItem('Turmeric'),
    FoodItem('Horseradish'),
    FoodItem('Wasabi'),
    FoodItem('Jicama'),
    FoodItem('Bamboo Shoots'),
    FoodItem('Water Chestnuts'),
    FoodItem('Lotus Root'),
    FoodItem('Seaweed'),
    FoodItem('Kelp'),
    FoodItem('Nori'),
    FoodItem('Wakame'),
    FoodItem('Spirulina'),
    FoodItem('Chlorella'),
    FoodItem('Alfalfa'),
    FoodItem('Sprouts'),
    FoodItem('Microgreens'),
    FoodItem('Herbs'),
    FoodItem('Basil'),
    FoodItem('Oregano'),
    FoodItem('Thyme'),
    FoodItem('Rosemary'),
    FoodItem('Sage'),
    FoodItem('Mint'),
    FoodItem('Dill'),
    FoodItem('Cilantro'),
    FoodItem('Parsley'),
    FoodItem('Chives'),
    FoodItem('Tarragon'),
    FoodItem('Bay Leaves'),
    FoodItem('Lemongrass'),
    FoodItem('Lavender'),
    FoodItem('Marjoram'),
    FoodItem('Savory'),
    FoodItem('Sorrel'),
    FoodItem('Stevia'),
    FoodItem('Summer Savory'),
    FoodItem('Winter Savory'),
    FoodItem('Hyssop'),
    FoodItem('Catnip'),
    FoodItem('Borage'),
    FoodItem('Chamomile'),
    FoodItem('Lemon Balm'),
    FoodItem('Calendula'),
    FoodItem('Fennel'),
    FoodItem('Dandelion'),
    FoodItem('Chickweed'),
    FoodItem('Nasturtium'),
    FoodItem('Purslane'),
    FoodItem('Radicchio'),
    FoodItem('Endive'),
    FoodItem('Escarole'),
    FoodItem('Watercress'),
    FoodItem('Mizuna'),
    FoodItem('Tat Soi'),
    FoodItem('Bok Choy'),
    FoodItem('Napa Cabbage'),
    FoodItem('Chinese Broccoli'),
    FoodItem('Gai Lan'),
    FoodItem('Mizuna'),
    FoodItem('Komatsuna'),
    FoodItem('Shiso'),
    FoodItem('Upland Cress'),
    FoodItem('Dandelion Greens'),
    FoodItem('Beet Greens'),
    FoodItem('Turnip Greens'),
    FoodItem('Radish Greens'),
    FoodItem('Mustard Greens'),
    FoodItem('Chard'),
    FoodItem('Sorrel'),
    FoodItem('Amaranth Leaves'),
    FoodItem('Malabar Spinach'),
    FoodItem('Orach'),
    FoodItem('Miner’s Lettuce'),
    FoodItem('Perilla'),
    FoodItem('Fenugreek'),
    FoodItem('Chickpeas'),
    FoodItem('Lentils'),
    FoodItem('Black Beans'),
    FoodItem('Kidney Beans'),
    FoodItem('Navy Beans'),
    FoodItem('Pinto Beans'),
    FoodItem('Great Northern Beans'),
    FoodItem('Lima Beans'),
    FoodItem('Fava Beans'),
    FoodItem('Adzuki Beans'),
    FoodItem('Mung Beans'),
    FoodItem('Edamame'),
    FoodItem('Soybeans'),
    FoodItem('Peanuts'),
    FoodItem('Almonds'),
    FoodItem('Walnuts'),
    FoodItem('Pecans'),
    FoodItem('Cashews'),
    FoodItem('Macadamia Nuts'),
    FoodItem('Brazil Nuts'),
    FoodItem('Hazelnuts'),
    FoodItem('Pine Nuts'),
    FoodItem('Pistachios'),
    FoodItem('Chestnuts'),
    FoodItem('Sunflower Seeds'),
    FoodItem('Pumpkin Seeds'),
    FoodItem('Sesame Seeds'),
    FoodItem('Chia Seeds'),
    FoodItem('Flax Seeds'),
    FoodItem('Hemp Seeds'),
    FoodItem('Poppy Seeds'),
    FoodItem('Cumin Seeds'),
    FoodItem('Caraway Seeds'),
    FoodItem('Fennel Seeds'),
    FoodItem('Celery Seeds'),
    FoodItem('Nigella Seeds'),
    FoodItem('Mustard Seeds'),
    FoodItem('Coriander Seeds'),
    FoodItem('Fenugreek Seeds'),
    FoodItem('Dill Seeds'),
    FoodItem('Anise Seeds'),
    FoodItem('Basil Seeds'),
    FoodItem('Squash Blossoms'),
    FoodItem('Edible Flowers'),
    FoodItem('Rose Petals'),
    FoodItem('Lavender Flowers'),
    FoodItem('Hibiscus Flowers'),
    FoodItem('Violets'),
    FoodItem('Nasturtiums'),
    FoodItem('Calendula Flowers'),
    FoodItem('Borage Flowers'),
    FoodItem('Chive Blossoms'),
    FoodItem('Dandelion Flowers'),
    FoodItem('Pansies'),
    FoodItem('Lilacs'),
    FoodItem('Carnations'),
    FoodItem('Jasmine Flowers'),
    FoodItem('Snapdragons'),
    FoodItem('Marigold Flowers'),
    FoodItem('Fuchsia Flowers'),
    FoodItem('Daisies'),
    FoodItem('Bee Balm'),
    FoodItem('Clover Flowers'),
    FoodItem('Mallow Flowers'),
    FoodItem('Pea Shoots'),
    FoodItem('Broccoli Raab'),
    FoodItem('Broccolini'),
    FoodItem('Rapini'),
    FoodItem('Rapeseed Greens'),
    FoodItem('Brussels Tops'),
    FoodItem('Kohlrabi'),
    FoodItem('Celeriac'),
    FoodItem('Salsify'),
    FoodItem('Skirret'),
    FoodItem('Taro'),
    FoodItem('Yautia'),
    FoodItem('Ube'),
    FoodItem('Purple Sweet Potato'),
    FoodItem('Jewel Yam'),
    FoodItem('Okinawan Sweet Potato'),
    FoodItem('Japanese Sweet Potato'),
    FoodItem('New Zealand Spinach'),
    FoodItem('Nopal'),
    FoodItem('Prickly Pear'),
  ];